# Generated by Django 5.2.16 on 2026-08-23 12:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=80, verbose_name='Soyad')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Telefon nömrəsi')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ümumi məbləğ')),
                ('status', models.CharField(choices=[('pending', 'Gözləmədə'), ('ready', 'Təhvil almağa hazırdır'), ('completed', 'Tamamlandı'), ('cancelled', 'Ləğv edildi')], default='pending', max_length=15, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sifariş tarixi')),
            ],
            options={
                'verbose_name': 'Sifariş',
                'verbose_name_plural': 'Sifarişlər',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Ad')),
                ('part_number', models.CharField(max_length=80, unique=True, verbose_name='Hissə nömrəsi')),
                ('category', models.CharField(max_length=100, verbose_name='Kateqoriya')),
                ('compatibility', models.CharField(blank=True, max_length=120, verbose_name='Avtomobil markası')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Qiymət')),
                ('image_url', models.URLField(blank=True, verbose_name='Şəkil ünvanı')),
                ('is_available', models.BooleanField(default=True, verbose_name='Mövcuddur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
            ],
            options={
                'verbose_name': 'Məhsul',
                'verbose_name_plural': 'Məhsullar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Miqdar')),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Alış qiyməti')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order', verbose_name='Sifariş')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product', verbose_name='Məhsul')),
            ],
            options={
                'verbose_name': 'Sifariş məhsulu',
                'verbose_name_plural': 'Sifariş məhsulları',
            },
        ),
    ]
