# Generated by Django 5.2.16 on 2026-08-25 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Mağaza istifadəçisi'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('pickup', 'Özüm götürəcəyəm'), ('paid_taxi', 'Ödənişli taksi ilə göndərilsin'), ('free_delivery', 'Pulsuz 1-2 günə çatdırılma')], default='pickup', max_length=20, verbose_name='Çatdırılma üsulu'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Ödənilməyib'), ('paid', 'Ödənilib')], default='unpaid', max_length=10, verbose_name='Ödəniş statusu'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Soyad'),
        ),
    ]
