# Generated by Django 5.2.16 on 2026-08-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_storeprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefon nömrəsi'),
        ),
    ]
