# Generated by Django 5.2.16 on 2026-08-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_level',
            field=models.CharField(choices=[('high', 'Çox'), ('medium', 'Orta'), ('low', 'Az')], default='medium', max_length=6, verbose_name='İstifadəçi üçün miqdar'),
        ),
    ]
